spring:
  cloud:
    gateway:
      routes[0]:
        id: payment-service
        predicates[0]: Path=/api/payment
        uri: lb://payment-service
      routes[1]:
        id: internal-service
        predicates[0]: Path=/api/internal
        uri: lb://internal-service
      routes[2]:
        id: internal-service
        predicates[0]: Path=/api/internal/**
        uri: lb://internal-service

  application:
    name: api-gateway


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}