server:
  port: 8091

spring:
  application:
    name: internal-service
#  profiles:
#    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/internal-services
    username: postgres
    password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create


#  sql:
#    init:
#      mode: always


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

app:
  jwt:
    secret: secret